package hiber.util.view.pojo;
// Generated May 13, 2020 12:45:42 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private String bookid;
     private Bookcat bookcat;
     private String title;
     private String publishinghouse;
     private Date dateofpub;
     private String author;
     private Integer pages;

    public Book() {
    }

	
    public Book(String bookid) {
        this.bookid = bookid;
    }
    public Book(String bookid, Bookcat bookcat, String title, String publishinghouse, Date dateofpub, String author, Integer pages) {
       this.bookid = bookid;
       this.bookcat = bookcat;
       this.title = title;
       this.publishinghouse = publishinghouse;
       this.dateofpub = dateofpub;
       this.author = author;
       this.pages = pages;
    }
   
    public String getBookid() {
        return this.bookid;
    }
    
    public void setBookid(String bookid) {
        this.bookid = bookid;
    }
    public Bookcat getBookcat() {
        return this.bookcat;
    }
    
    public void setBookcat(Bookcat bookcat) {
        this.bookcat = bookcat;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPublishinghouse() {
        return this.publishinghouse;
    }
    
    public void setPublishinghouse(String publishinghouse) {
        this.publishinghouse = publishinghouse;
    }
    public Date getDateofpub() {
        return this.dateofpub;
    }
    
    public void setDateofpub(Date dateofpub) {
        this.dateofpub = dateofpub;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Integer getPages() {
        return this.pages;
    }
    
    public void setPages(Integer pages) {
        this.pages = pages;
    }




}


