package hiber.util.view.pojo;
// Generated May 13, 2020 12:45:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bookcat generated by hbm2java
 */
public class Bookcat  implements java.io.Serializable {


     private String categoid;
     private String categoname;
     private Set books = new HashSet(0);

    public Bookcat() {
    }

	
    public Bookcat(String categoid) {
        this.categoid = categoid;
    }
    public Bookcat(String categoid, String categoname, Set books) {
       this.categoid = categoid;
       this.categoname = categoname;
       this.books = books;
    }
   
    public String getCategoid() {
        return this.categoid;
    }
    
    public void setCategoid(String categoid) {
        this.categoid = categoid;
    }
    public String getCategoname() {
        return this.categoname;
    }
    
    public void setCategoname(String categoname) {
        this.categoname = categoname;
    }
    public Set getBooks() {
        return this.books;
    }
    
    public void setBooks(Set books) {
        this.books = books;
    }




}


