package hiber.util.view.pojo;
// Generated May 13, 2020 12:45:42 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Checkout generated by hbm2java
 */
public class Checkout  implements java.io.Serializable {


     private String clientId;
     private String clientNames;
     private String bookId;
     private String bookTitle;
     private String author;
     private Date issuedate;
     private String comment;

    public Checkout() {
    }

	
    public Checkout(String clientId) {
        this.clientId = clientId;
    }
    public Checkout(String clientId, String clientNames, String bookId, String bookTitle, String author, Date issuedate, String comment) {
       this.clientId = clientId;
       this.clientNames = clientNames;
       this.bookId = bookId;
       this.bookTitle = bookTitle;
       this.author = author;
       this.issuedate = issuedate;
       this.comment = comment;
    }
   
    public String getClientId() {
        return this.clientId;
    }
    
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }
    public String getClientNames() {
        return this.clientNames;
    }
    
    public void setClientNames(String clientNames) {
        this.clientNames = clientNames;
    }
    public String getBookId() {
        return this.bookId;
    }
    
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }
    public String getBookTitle() {
        return this.bookTitle;
    }
    
    public void setBookTitle(String bookTitle) {
        this.bookTitle = bookTitle;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Date getIssuedate() {
        return this.issuedate;
    }
    
    public void setIssuedate(Date issuedate) {
        this.issuedate = issuedate;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


