package hiber.util.view.pojo;
// Generated May 13, 2020 12:45:42 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Checkin generated by hbm2java
 */
public class Checkin  implements java.io.Serializable {


     private String bokid;
     private String booktitle;
     private String bookauthor;
     private Date returnDate;
     private String comment;

    public Checkin() {
    }

	
    public Checkin(String bokid) {
        this.bokid = bokid;
    }
    public Checkin(String bokid, String booktitle, String bookauthor, Date returnDate, String comment) {
       this.bokid = bokid;
       this.booktitle = booktitle;
       this.bookauthor = bookauthor;
       this.returnDate = returnDate;
       this.comment = comment;
    }
   
    public String getBokid() {
        return this.bokid;
    }
    
    public void setBokid(String bokid) {
        this.bokid = bokid;
    }
    public String getBooktitle() {
        return this.booktitle;
    }
    
    public void setBooktitle(String booktitle) {
        this.booktitle = booktitle;
    }
    public String getBookauthor() {
        return this.bookauthor;
    }
    
    public void setBookauthor(String bookauthor) {
        this.bookauthor = bookauthor;
    }
    public Date getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


