package hiber.util.view.pojo;
// Generated May 13, 2020 12:45:42 AM by Hibernate Tools 4.3.1



/**
 * Signup generated by hbm2java
 */
public class Signup  implements java.io.Serializable {


     private String username;
     private String name;
     private String password;

    public Signup() {
    }

	
    public Signup(String username) {
        this.username = username;
    }
    public Signup(String username, String name, String password) {
       this.username = username;
       this.name = name;
       this.password = password;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


